config/routes.rb
Capitalist::Application.routes.draw do
  shallow do
    resources :assets do
      resources :positions do
        resources :purchases, :sales
      end
    end
  end
  root :to => "assets#index"
end

app/models/position.rb
class Position < ActiveRecord::Base
  attr_accessible :asset_id
  
  belongs_to :asset      
  has_many :transactions, :order => "date ASC", :dependent => :destroy
  has_many :purchases, :order => "date ASC"
  has_many :sales, :order => "date ASC"
  
  validates_presence_of :asset_id

  def status
    if !transactions.empty? && current_units == 0
      'Closed'
    else
      'Open'
    end
  end    

  def units(a_date=Time.now)
    bought = purchases.where("date <= ?", a_date).sum('units')
    sold = sales.where("date <= ?", a_date).sum('units')    
    bought - sold
  end

  def current_units
    units
  end              
  
  def average_unit_price                           
    if status == "Closed" || transactions.empty?
      0
    else
      investment_value_of_purchases = purchases.sum('value') 
      ( investment_value_of_purchases - 
        investment_value_of_sales ) / current_units
    end                          
  end                            
    
  private
  
  def investment_value_of_sales
    sold = 0
    if !sales.empty?
      sales.each do |sale|
        invested_value = purchases.where("date <= ?", sale.date).sum('value')
        invested_units = units(sale.date) + sale.units
        effective_purchase_price = invested_value / invested_units
        sold += effective_purchase_price * sale.units
      end
    end
    sold
  end  
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  def index
    @asset = Asset.find(params[:asset_id])    
    @positions = @asset.positions
  end

  def show
    @position = Position.find(params[:id])
  end

  def new
    @asset = Asset.find(params[:asset_id])    
    @position = @asset.positions.build
  end

  def create
    @asset = Asset.find(params[:asset_id])    
    @position = Position.new(params[:position])
    if @position.save
      redirect_to position_path(@position), 
        :notice => "Successfully created position."
    else
      render :action => 'new'
    end
  end

  def edit
    @position = Position.find(params[:id]) 
  end

  def update
    @position = Position.find(params[:id])
    if @position.update_attributes(params[:position])
      redirect_to position_path(@position), 
        :notice  => "Successfully updated position."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @position = Position.find(params[:id])
    asset = @position.asset
    @position.destroy
    redirect_to asset_positions_url(asset), 
      :notice => "Successfully destroyed position."
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.haml
= simple_form_for [@asset, @position] do |f|
  = f.error_messages
  = f.association :asset, :as => :hidden
  = f.button :submit

app/views/positions/_table.html.haml
%table#positions
  %tr
    %th Asset
    %th Units
    %th Status
    %th Average Unit Price
  - for position in @positions
    %tr.position
      %td= position.asset.name
      %td.numeric= position.current_units
      %td= position.status
      %td.numeric= number_to_currency(position.average_unit_price, :unit => '£')
      %td.nav= link_to 'Show', position_path(position)
      %td.nav= link_to 'Edit', edit_position_path(position)
      %td.nav= link_to 'Destroy', position, :confirm => 'Are you sure?', :method => :delete
      

app/views/positions/edit.html.haml
- title "Edit Position"

= render 'form'
  
%p= link_to "Asset Position List", asset_path(@position.asset)

app/views/positions/index.html.haml
- title "Positions"

= render :partial => 'table'

%p= link_to "New Position", new_asset_position_path(@asset)

app/views/positions/new.html.haml
- title "New Position"

= render 'form'

%p= link_to "Back to List", asset_positions_path(@asset)

app/views/positions/show.html.haml
- title "Summary of #{@position.asset.name} Holdings in Position #{@position.id}"

%ul
  %li= link_to "View all positions for this asset", asset_path(@position.asset)
  %li= link_to "View position purchases", position_purchases_path(@position)
  %li= link_to "View position sales", position_sales_path(@position)