config/routes.rb
Capitalist::Application.routes.draw do
  shallow do
    resources :assets do
      resources :positions do
        resources :purchases, :sales
      end
    end
  end
  root :to => "assets#index"
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def index
    @position = Position.find(params[:position_id])
    @transactions = @position.purchases
  end
  
  def new
    @position = Position.find(params[:position_id])
    @transaction = @position.purchases.build
  end

  def create
    @position = Position.find(params[:position_id])
    @transaction = Purchase.new(params[:purchase])
    if @transaction.save
      redirect_to position_purchases_url(@position), 
        :notice => "Successfully created transaction."
    else
      render :action => 'new'
    end
  end

  def edit
    @transaction = Purchase.find(params[:id])
    @position_for_route = @transaction.position
  end     

  def update
    @transaction = Purchase.find(params[:id])
    @position_for_route = @transaction.position
    if @transaction.update_attributes(params[:purchase])
      redirect_to position_purchases_url(@transaction.position), 
        :notice => "Successfully updated transaction."
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @transaction = Purchase.find(params[:id])
    position = @transaction.position
    @transaction.destroy
    redirect_to position_purchases_url(position), 
      :notice => "Successfully destroyed transaction."
  end
end

app/views/purchases/edit.html.haml
- title "Edit Transaction"

= render 'transactions/form'

%p= link_to "Back to List", position_purchases_path(@transaction.position)

app/views/purchases/index.html.haml
- title "Purchasing transactions for #{@position.asset.name}"

= render :partial => 'transactions/index'

%ul
  %li= link_to "Back to the position summary", position_path(@position)                                                                            
  %li= link_to "New Purchase", new_position_purchase_path(@position)
  

app/views/purchases/new.html.haml
- title "New Transaction"

= render 'transactions/form'

%p= link_to "Back to List", position_purchases_path(@position)