config/routes.rb
Capitalist::Application.routes.draw do
  shallow do
    resources :assets do
      resources :positions do
        resources :purchases, :sales
      end
    end
  end
  root :to => "assets#index"
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  attr_accessible :name, :description
  has_many :positions, :dependent => :destroy
  
  validates :name, :presence => true, 
            :uniqueness => true,
            :length => {:maximum => 20}

  def current_units 
    total = 0
    positions.each do |position|
      total += position.current_units
    end
    total
  end  
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  def index
    @assets = Asset.all
  end

  def show
    @asset = Asset.find(params[:id])
    @positions = @asset.positions
  end

  def new
    @asset = Asset.new
  end

  def create
    @asset = Asset.new(params[:asset])
    if @asset.save
      redirect_to assets_url, :notice => "Successfully created asset."
    else
      render :action => 'new'
    end
  end

  def edit
    @asset = Asset.find(params[:id])
  end

  def update
    @asset = Asset.find(params[:id])
    if @asset.update_attributes(params[:asset])
      redirect_to assets_url, :notice  => "Successfully updated asset."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy
    redirect_to assets_url, :notice => "Successfully destroyed asset."
  end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_form.html.haml
= simple_form_for @asset do |f|
  = f.error_messages
  = f.input :name
  = f.input :description
  = f.button :submit

app/views/assets/edit.html.haml
- title "Edit Asset"

= render 'form'

%p
  = link_to "View All", assets_path

app/views/assets/index.html.haml
- title "Assets"

%table
  %tr
    %th Name
    %th.description Description
  - for asset in @assets
    %tr
      %td= asset.name
      %td= asset.description
      %td.nav= link_to 'Show', asset_path(asset)
      %td.nav= link_to 'Edit', edit_asset_path(asset)
      %td.nav= link_to 'Destroy', asset, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Asset", new_asset_path

app/views/assets/new.html.haml
- title "New Asset"

= render 'form'

%p= link_to "Back to List", assets_path

app/views/assets/show.html.haml
- title "Summary of #{@asset.name} Holdings"

%h2 Position Summary

%p#total_units= "You currently hold #{@asset.current_units} units"

%h2 Positions

= render :partial => 'positions/table'            

%ul
  %li= link_to "View All", assets_path
  %li= link_to "New Position", new_asset_position_path(@asset)